name: Local Runner Test

on:
  workflow_dispatch:

jobs:
  test-local-runner:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Show machine information
        run: |
          echo "GitHub Action is running locally"
          echo "Hostname:"
          hostname
          echo "Working directory:"
          pwd

      - name: Check Node
        run: |
          node --version
          npm --version

      - name: Check Git
        run: git --version

      - name: Check Docker
        run: |
          docker --version
          docker compose version
          docker ps

      - name: Check Flyway
        run: flyway -v